hrconsole/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :skills , :employees , :leads
end

hrconsole/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hrconsole/app/models/employee.rb
class Employee < ApplicationRecord
  has_and_belongs_to_many :skills
  belongs_to :lead
  belongs_to :project
  validates :name, presence: true
end

hrconsole/app/models/lead.rb
class Lead < ApplicationRecord
  has_many :employees
end

hrconsole/app/models/project.rb
class Project < ApplicationRecord
  has_many :employees
end

hrconsole/app/models/skill.rb
class Skill < ApplicationRecord
  validates :skill, presence: true
  has_and_belongs_to_many :employees

end

hrconsole/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

hrconsole/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new()
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render 'edit'
    end
  end
  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render 'new'
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :age, :designation,  :lead_id, :project_id, :skill_ids => [])
  end
end

hrconsole/app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def index
    @leads = Lead.all
  end

  def show
    @lead = Lead.find(params[:id])
    @emp_list_sorted = @lead.employees.sort {|a,b| b.skills.count <=> a.skills.count}
  end

  def new
  end

  def create
    @lead = Lead.new(lead_params)
    @lead.save
    redirect_to @lead
  end

  def destroy
  end

  private

  def lead_params
    params.require(:lead).permit(:lead_name, :employee_ids => [])
  end
end

hrconsole/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def new
  end

  def index
    @skills = Skill.all
  end

  def create
    @skill = Skill.new(skill_params)
    @skill.save
    redirect_to @skill
  end

  def show
    @skill = Skill.find(params[:id])
  end

  private

  def skill_params
    params.require(:skill).permit(:skill, :employee_ids => [])
  end
end

hrconsole/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

hrconsole/app/helpers/application_helper.rb
module ApplicationHelper
end

hrconsole/app/helpers/employees_helper.rb
module EmployeesHelper
end

hrconsole/app/helpers/leads_helper.rb
module LeadsHelper
end

hrconsole/app/helpers/skills_helper.rb
module SkillsHelper
end

hrconsole/app/helpers/welcome_helper.rb
module WelcomeHelper
end

hrconsole/app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>
  <% if @employee.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:
        </h2>
        <ul>
          <% @employee.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  <p>
      <%= f.label :Employee_Name %><br>
      <%= f.text_field :name %>
  </p>

   <p>
      <%= f.label :Age %><br>
      <%= f.number_field :age%>
  </p>

   <p>
      <%= f.label :Designation %><br>
      <%= f.text_field :designation%>
  </p>

  <p>
      <%= f.label :Skills %><br>
      <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :skill do |m| %>
        <%= m.check_box %> <%= m.label %>
    <% end %>
  </p>

  <p>
      <%= f.label :Team_lead%><br>
      <%= f.collection_radio_buttons :lead_id, Lead.all, :id, :lead_name do |m| %>
        <%= m.radio_button %> <%= m.label %>
      <% end %>
  </p>

  <p>
    <%= f.label :Project%> <br>
    <%= f.collection_select :project_id, Project.order(:project),:id,:project, include_blank: true %>
  </p>

  <p>
      <%= f.submit %>
  </p>
<% end %>

hrconsole/app/views/employees/edit.html.erb
<h1> Edit the employee Details </h1>
<%= render 'form' %>

hrconsole/app/views/employees/index.html.erb
<h1>List of employees</h1>
<ul>
  <% @employees.each do |employee| %>
    <li><a href="/employees/<%=employee[:id]%>"><%= employee.name %></li>
  <% end %>
</ul>
<%= link_to 'Create new Employee', new_employee_path %>
<p><%= link_to 'home', welcome_index_path %></p>

hrconsole/app/views/employees/new.html.erb
<h1> Page to create New employee </h1>
<%= render 'form' %>
<%= link_to 'back', employees_path %>

hrconsole/app/views/employees/show.html.erb
<h1> Employee Details </h1>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employee.age %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @employee.designation %>
</p>

<p>
  <strong>Skills:</strong>
  <% @employee.skills.each do |skill| %>
  <%= skill.skill %>
  <% end %>
</p>

<p>
  <strong>Lead:</strong>
  <%= @employee.lead.lead_name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @employee.project.project %>
</p>

<p><%= link_to 'Back to list', employees_path %></p>
<p><%= link_to 'Edit Details', edit_employee_path(@employee) %></p>
<p><%= link_to 'Delete employee', employee_path(@employee),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %></p>
<p><%= link_to 'Create new Employee', new_employee_path %></p>

hrconsole/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hrconsole</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hrconsole/app/views/leads/index.html.erb
<h1> list of leads</h1>

<ul>
  <% @leads.each do |lead| %>
      <li><a href="/leads/<%=lead[:id]%>"><%= lead.lead_name %></li>
  <% end %>
</ul>
<%= link_to 'Add new Lead', new_lead_path %>
<p>Click on <%= link_to 'home', welcome_index_path %>

hrconsole/app/views/leads/new.html.erb
<h1> Page to add new leads</h1>

<%= form_for :lead, url: leads_path do |f| %>
  <p>
      <%= f.label :lead_name %><br>
      <%= f.text_field :lead_name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

hrconsole/app/views/leads/show.html.erb
<p>
  <strong>Lead:</strong>
  <%= @lead.lead_name %>
</p>

<table>
  <tr>
    <th> Employee </th> <th> Skills </th>
  </tr>
  <% @emp_list_sorted.each do |employee| %>
    <tr>
      <td> <%= employee.name %> </td> <td> <%= employee.skills.count %> </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create new Employee', new_employee_path %>
<p><%= link_to 'back to list', leads_path %></p>

hrconsole/app/views/skills/index.html.erb
<h1> Listing all skills </h1>
<ul>
  <% @skills.each do |skill| %>
      <li><%= skill.skill %></li>
  <% end %>
</ul>
<%= link_to 'Add new Skill', new_skill_path %>
<p>Click on <%= link_to 'home', welcome_index_path %>

hrconsole/app/views/skills/new.html.erb
<h1> Page to add new skills</h1>

<%= form_for :skill, url: skills_path do |f| %>
  <p>
    <%= f.label :skill %><br>
    <%= f.text_field :skill %>
  </p>

  <%= f.submit %>
  <% end %>
  <%= link_to 'back', skills_path %>

hrconsole/app/views/skills/show.html.erb
<p>
  <strong>Skill:</strong>
  <%= @skill.skill %>
</p>

hrconsole/app/views/welcome/index.html.erb
<h1>Welcome page</h1>

<p> Click on <%= link_to 'Employees List', employees_path %> to View List of Employees</p>
<p>Click on <%= link_to 'Team Lead List', leads_path %> to view the list of Team Leads</p>
<p>Click on <%= link_to 'skills List', skills_path %> to view the list of skills</p>